Getting started page for usability study
PowerShell/ProjectMercury pull request #236
Opened 2024-09-30 17:53 UTC by StevenBucher98

# PR Summary

A getting started page that will be used for usability study and eventually the final doc pages.

## PR Context

2024-09-30 19:26 UTC, sdwheeler commented on docs/GettingStarted.md
> +![A Gif showing Azure Agent in action](/docs/media/AzureAgent.gif)
```suggestion
![An animation showing Azure Agent in action.](/docs/media/AzureAgent.gif)
```

2024-09-30 19:34 UTC, sdwheeler commented on docs/GettingStarted.md
> +![A Gif showing Inserting Code with AIShell](/docs/media/InsertCode.gif)
```suggestion
When you are chatting with the agent, you can use the `/code post` command to automatically insert
the code from the response into the working shell. This is the simplest way to quickly get the code
you need to run in your shell. You can also use the hot key <kbd>Ctrl</kbd>+<kbd>d</kbd>,
<kbd>Ctrl</kbd>+<kbd>d</kbd> to insert the code into the working shell.

![An animation showing Inserting Code with AIShell.](/docs/media/InsertCode.gif)

```

2024-09-30 19:44 UTC, sdwheeler commented on docs/GettingStarted.md
> +| <kbd>Ctrl+d, \<n\></kbd>  | `/code post <n>` | Post the _n-th_ generated code snippet to the connected application |
```suggestion
AIShell has key bindings for the `/code` command. They key bindings are currently hard-coded, but
custom key bindings will be supported in future releases.

|                       Key bindings                       |     Command      |                            Functionality                            |
| -------------------------------------------------------- | ---------------- | ------------------------------------------------------------------- |
| <kbd>Ctrl+d</kbd><kbd>Ctrl</kbd>+<kbd>c</kbd>            | `/code copy`     | Copy _all_ the generated code snippets to clipboard                 |
| <kbd>Ctrl</kbd>+<kbd>\<n\></kbd>                         | `/code copy <n>` | Copy the _n-th_ generated code snippet to clipboard                 |
| <kbd>Ctrl</kbd>+<kbd>d</kbd><kbd>Ctrl</kbd>+<kbd>d</kbd> | `/code post`     | Post _all_ the generated code snippets to the connected application |
| <kbd>Ctrl</kbd>+<kbd>d</kbd><kbd>\<n\></kbd>             | `/code post <n>` | Post the _n-th_ generated code snippet to the connected application |
```

2024-09-30 19:46 UTC, sdwheeler commented on docs/GettingStarted.md
> +AI model open to help you resolve the error.
```suggestion
If you encounter an error in your working terminal, you can use the `Resolve-Error` cmdlet to send
that error to the open AIShell window for resolution. This command asks the AI model to help you
resolve the error.
```

2024-10-01 19:11 UTC, mikefrobbins requested changes
See my comments

2024-10-01 19:11 UTC, mikefrobbins commented on docs/GettingStarted.md
> +Here is a quick demo showing the Azure Agent in action:
```suggestion
Here's a quick demo showing the Azure Agent in action:
```

2024-10-03 04:30 UTC, daxian-dbw approved these changes

2024-10-03 16:18 UTC, sdwheeler approved these changes

2024-10-03 16:19 UTC, merged