Update Installation Id Initialization to support both AzPS and AzCLI on Unbuntu
PowerShell/ProjectMercury pull request #260
Opened 2024-10-30 04:08 UTC by NoriZC

# PR Summary

Tested on both ubuntu dockers for azps and azcli.
- AzCLI:
- ![image](https://github.com/user-attachments/assets/44d21a8a-e73d-4f2a-ad1b-a478350a6598)

- AzPSH:
- ![image](https://github.com/user-attachments/assets/beab59be-9fac-4f64-90e1-2d6dc7696e9d)

## PR Context

2024-10-30 04:34 UTC, daxian-dbw commented
@NoriZC Please revert the changes in `AzureAgent.cs`. We will put off telemetry code changes until the metrics for each telemetry are well defined.

2024-10-30 04:36 UTC, NoriZC commented
> @NoriZC Please revert the changes in `AzureAgent.cs`. We will put off telemetry code changes until the metrics for each telemetry are well defined.

OK, I will seperate this PR soon

2024-10-30 04:37 UTC, daxian-dbw requested changes

2024-10-30 04:37 UTC, daxian-dbw commented on shell/agents/Microsoft.Azure.Agent/Telemetry.cs
> +        string azPSHProfilePath = azureConfigDir ?? Path.Combine(userProfile, ".Azure", "AzureRmContextSettings.json");
`azureConfigDir` is a folder path, so when `AZURE_CONFIG_DIR` is defined in environment variable, `azCLIProfilePath` and `azPSHProfilePath` will be set to the folder path in your code.

2024-10-30 04:38 UTC, daxian-dbw commented
> OK, I will seperate this PR soon

Do not work on the new changes yet. We need to metrics to be well defined before start coding work. We don't want to make changes again and again.

2024-10-30 04:44 UTC, daxian-dbw commented
@NoriZC You can continue with fixing installation id in this PR, but please revert the unrelated changes.

2024-10-31 00:52 UTC, daxian-dbw approved these changes

2024-10-31 00:53 UTC, merged